In [1]:
#import libery
import tensorflow as tf

# matrix

In [2]:
#matrix 1,1
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [3]:
#2,3
x=tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [4]:
#ones
x=tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [5]:
#zeros
x=tf.zeros((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
#identity matrix
x=tf.eye(3)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [7]:
#3,3 random value
x=tf.random.normal((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.4242038 ,  1.7373866 ,  1.6495475 ],
       [ 1.1744982 ,  1.6519517 ,  0.48970205],
       [-1.105063  , -0.8996307 ,  0.0810873 ]], dtype=float32)>

In [8]:
#random value limitaion genarate
x=tf.random.uniform((3,3),minval=0,maxval=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6975763 , 0.06647587, 0.06573331],
       [0.31950974, 0.72400737, 0.6856934 ],
       [0.2492019 , 0.6579981 , 0.14625561]], dtype=float32)>

In [9]:
#value genarate
x=tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [10]:
#odd value
x=tf.range(start=1,limit=10,delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [11]:
#even value
x=tf.range(start=0,limit=10,delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [12]:
#weight 
tf.cast(x,dtype=tf.float64)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0., 2., 4., 6., 8.])>

# mathematical oparation

In [13]:
#add
x=tf.constant([1,2,3])
y=tf.constant([5,6,7])
tf.add(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  8, 10], dtype=int32)>

In [14]:
#subtract
tf.subtract(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-4, -4, -4], dtype=int32)>

In [15]:
#divide
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.2       , 0.33333333, 0.42857143])>

In [16]:
#multiply
tf.multiply(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 12, 21], dtype=int32)>

In [17]:
#multiply and sum
tf.tensordot(x,y,axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=38>

In [18]:
#sqr
x**2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

# indexing

In [19]:
x=tf.constant([0,1,2,3,4,5,6,7,8,9])
x[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [20]:
x[3:]

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [21]:
x[:-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [22]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [23]:
len(x)

10

In [24]:
x[2:7]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [25]:
x[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [26]:
x=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
x[1:3]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [28]:
x[2:3]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[7, 8, 9]], dtype=int32)>

In [29]:
x[0:2]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [30]:
x[1:2]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[4, 5, 6]], dtype=int32)>

# Reshaping

In [31]:
x=tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [32]:
x=tf.reshape(x,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [33]:
#change row to column
x=tf.transpose(x,perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>